import { trpc } from "@/lib/trpc";
import { ArrowRight, Image as ImageIcon } from "lucide-react";
import { useLocation } from "wouter";

export default function GalleryPage() {
  const [, navigate] = useLocation();
  const { data: galleries, isLoading } = trpc.galleries.list.useQuery({ page: 1, limit: 20 });
  return <div className="pb-10"><section className="grid overflow-hidden rounded-[1.6rem] border border-white/[0.14] bg-[#202630]/78 px-6 py-10 shadow-xl shadow-black/10 sm:px-10 sm:py-14 lg:grid-cols-12"><div className="lg:col-span-6"><p className="text-sm text-slate-300">图片集</p><h1 className="display-title mt-4 text-5xl sm:text-6xl">图像，不是<br /><span className="display-accent">文章的背景。</span></h1></div><div className="mt-7 max-w-md lg:col-span-4 lg:col-start-9 lg:mt-2"><p className="copy-lede">这里保存那些与文字同样值得回看的画面。公开展示的图片均来自真实上传，不用示例内容填充。</p></div></section>{isLoading ? <div className="grid min-h-80 place-items-center"><p className="text-sm text-slate-300">正在读取图片集…</p></div> : galleries?.length ? <section className="mt-6 grid gap-5 md:grid-cols-2">{galleries.map((gallery: any) => { const imageUrl = gallery.coverImage || gallery.coverUrl || gallery.thumbnailUrl; return <button key={gallery.id} type="button" onClick={() => navigate(`/gallery/${gallery.id}`)} className="group overflow-hidden rounded-2xl border border-white/[0.13] bg-[#202630]/64 text-left shadow-lg shadow-black/10 transition-colors hover:border-[#bce8eb]/42" aria-label={`打开图片集：${gallery.title}`}><div className="article-cover aspect-[1.45]">{imageUrl ? <img src={imageUrl} alt={gallery.title} loading="lazy" /> : <div className="grid h-full place-items-center bg-[#15191f]/72"><span className="text-sm text-slate-300">暂未设置封面</span></div>}</div><div className="flex items-start justify-between gap-5 p-5"><div><h2 className="text-xl font-medium text-white transition-colors group-hover:text-[#d6fbfc]">{gallery.title}</h2>{gallery.description && <p className="mt-2 text-sm leading-6 text-slate-300">{gallery.description}</p>}</div><ArrowRight size={16} className="mt-1 shrink-0 text-slate-400 transition-transform group-hover:translate-x-1 group-hover:text-[#bce8eb]" /></div></button>; })}</section> : <section className="mt-6 grid min-h-96 place-items-center rounded-2xl border border-dashed border-white/[0.16] bg-[#202630]/52 px-5 text-center"><div><ImageIcon size={24} className="mx-auto text-slate-400" /><p className="mt-5 text-sm font-medium text-slate-200">这里还没有公开图片集</p><p className="mt-3 max-w-sm text-sm leading-7 text-slate-400">管理员创建图片集并上传真实图片后，内容会显示在这里。</p></div></section>}</div>;
}
