import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { useLocation } from "wouter";
import { ArrowRight, BookOpen, Clock3, Eye, RefreshCw, ShieldCheck } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { formatReadingTime } from "@/lib/readingTime";
import { splitHomePosts } from "@/lib/homePosts";
import { formatHomeQuote } from "@/lib/homeQuote";

const observatoryCover = "/manus-storage/observatory-night_fc4b375d.jpg";

function coverFor(post: any) { return post?.coverImage || observatoryCover; }
function formatDate(value: Date | string | null | undefined) { return value ? new Date(value).toLocaleDateString("zh-CN", { month: "long", day: "numeric" }) : "尚未发布"; }

export default function Home() {
  const { isAuthenticated, user } = useAuth();
  const isAdmin = isAuthenticated && user?.role === "admin";
  const [, navigate] = useLocation();
  const { data: posts, isLoading } = trpc.posts.list.useQuery({ page: 1, limit: 5 });
  const { featured, latest } = splitHomePosts<any>(posts?.data ?? []);
  const { data: quote, isFetching: isQuoteFetching, refetch: refetchQuote } = trpc.quote.current.useQuery(undefined, { staleTime: 1000 * 60 * 30, refetchOnWindowFocus: false });

  return <div className="pb-12">
    <section className="border-b border-white/[0.28] pb-10 pt-4 sm:pb-14 sm:pt-8" aria-labelledby="featured-post-heading"><div className="flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div className="max-w-2xl"><p className="editorial-kicker">MorroBlog · 个人技术札记</p><h1 id="featured-post-heading" className="display-title mt-3 text-4xl sm:text-5xl">本期精选</h1><div className="mt-4 max-w-xl border-l border-[#eab78c] pl-4 sm:pl-5"><p className="copy-lede text-[#fff8ed]" aria-live="polite">{formatHomeQuote(quote?.text || "正在摘取一句话…")}</p><div className="mt-3 flex flex-wrap items-center gap-x-4 gap-y-2 text-xs text-[#d0cfca]"><span className="font-mono tracking-[0.12em] text-[#d0f4ee]">此刻一言 / 公共接口</span>{quote?.source && <span>— {quote.source}</span>}<button type="button" onClick={() => void refetchQuote()} disabled={isQuoteFetching} className="inline-flex items-center gap-1 border-b border-white/[0.3] pb-1 text-[#e5e2db] transition-colors hover:border-[#d0f4ee] hover:text-[#d0f4ee] disabled:cursor-wait disabled:opacity-60" aria-label="从公开一言接口换一句"><RefreshCw size={12} className={isQuoteFetching ? "animate-spin" : ""} />{isQuoteFetching ? "更新中" : "换一句"}</button></div></div></div><div className="flex shrink-0 flex-col items-start gap-4 sm:items-end"><p className="max-w-xs text-sm leading-6 text-[#d0cfca] sm:text-right">从最近发布的内容里，挑出一篇值得先读的记录。</p>{isAdmin && <Button onClick={() => navigate("/admin")} className="editorial-button editorial-button-primary px-4"><ShieldCheck size={14} className="mr-2" />进入管理员视角</Button>}</div></div>
      {isLoading ? <div className="mt-8 grid animate-pulse overflow-hidden border border-white/[0.18] lg:grid-cols-12"><div className="min-h-[310px] bg-white/[0.06] lg:col-span-5" /><div className="min-h-[310px] bg-white/[0.1] lg:col-span-7" /></div> : featured ? <button type="button" onClick={() => navigate(`/posts/${featured.slug}`)} className="group mt-8 grid w-full overflow-hidden border border-white/[0.24] text-left transition-colors hover:border-[#d0f4ee]/70 lg:grid-cols-12" aria-label={`阅读精选文章：${featured.title}`}><div className="flex min-h-[320px] flex-col justify-between px-5 py-7 sm:px-8 sm:py-9 lg:col-span-5"><div><div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-[#d0cfca]"><span className="text-[#d0f4ee]">{featured.category?.name || "未分类"}</span><span>{formatDate(featured.publishedAt)}</span></div><h2 className="display-title mt-5 text-3xl leading-tight text-[#fff8ed] transition-colors group-hover:text-[#d0f4ee] sm:text-4xl">{featured.title}</h2><p className="mt-5 line-clamp-3 max-w-lg text-sm leading-7 text-[#dfddd7] sm:text-base">{featured.excerpt || "这篇记录暂未填写摘要。"}</p></div><div className="mt-8 flex flex-wrap items-center gap-x-4 gap-y-2 text-xs text-[#d5d5d0]"><span className="flex items-center gap-1.5"><Clock3 size={13} />{formatReadingTime(featured.content || "")}</span><span className="flex items-center gap-1.5"><Eye size={13} />{featured.viewCount || 0}</span><span className="flex items-center gap-1.5 text-[#d0f4ee]">阅读全文 <ArrowRight size={14} className="transition-transform group-hover:translate-x-1" /></span></div></div><div className="article-cover min-h-[255px] lg:col-span-7 lg:min-h-[430px]"><img src={coverFor(featured)} alt={featured.title} fetchPriority="high" /></div></button> : <div className="mt-8 border-y border-white/[0.2] py-14 text-center"><p className="editorial-kicker">暂时没有公开文章</p><p className="mt-3 text-[#e5e2db]">下一篇发布后，会首先出现在这里。</p></div>}
    </section>
    <section className="pt-14 sm:pt-20" aria-labelledby="latest-posts-heading"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="editorial-kicker">最近记录 · {String(posts?.total || 0).padStart(2, "0")} 篇文章</p><h2 id="latest-posts-heading" className="display-title mt-3 text-4xl sm:text-5xl">最新文章</h2></div><button onClick={() => navigate("/posts")} aria-label="浏览文章列表" className="group flex items-center gap-2 self-start border-b border-white/[0.35] pb-1 text-sm text-[#f4ede3] transition-colors hover:border-[#d0f4ee] hover:text-[#d0f4ee] sm:self-auto">全部文章 <ArrowRight size={15} className="transition-transform group-hover:translate-x-1" /></button></div>{isLoading ? <div className="mt-8 space-y-3" aria-label="正在读取最新文章"><div className="h-36 animate-pulse border-y border-white/[0.15] bg-white/[0.04]" /><div className="h-36 animate-pulse border-y border-white/[0.15] bg-white/[0.04]" /></div> : latest.length > 0 ? <div className="mt-8 divide-y divide-white/[0.2] border-y border-white/[0.2]">{latest.map((post: any, index: number) => <button key={post.id} type="button" onClick={() => navigate(`/posts/${post.slug}`)} className="group grid w-full cursor-pointer gap-5 py-5 text-left transition-colors hover:bg-white/[0.055] sm:grid-cols-[auto_minmax(0,1fr)_170px] sm:items-center sm:gap-8 sm:px-4 sm:py-7" aria-label={`阅读文章：${post.title}`}><span className="article-index order-2 sm:order-none">{String(index + 2).padStart(2, "0")}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-[#d5d5d0]"><span>{post.category?.name || "未分类"}</span><span>{formatDate(post.publishedAt)}</span></div><h3 className="mt-2 text-2xl font-medium leading-snug text-[#fff8ed] transition-colors group-hover:text-[#d0f4ee] sm:text-3xl">{post.title}</h3><p className="mt-2 line-clamp-2 max-w-2xl text-sm leading-7 text-[#dfddd7]">{post.excerpt || "尚未填写摘要。"}</p><div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-2 text-xs text-[#d5d5d0]"><span className="flex items-center gap-1.5"><Clock3 size={13} />{formatReadingTime(post.content || "")}</span><span className="flex items-center gap-1.5"><Eye size={13} />{post.viewCount || 0}</span><span className="flex items-center gap-1.5 text-[#d0f4ee]">阅读 <BookOpen size={13} /></span></div></div><div className="article-cover order-first aspect-[1.8] sm:order-none sm:aspect-[1.18]"><img src={coverFor(post)} alt={post.title} loading="lazy" /></div></button>)}</div> : featured ? <p className="mt-8 border-y border-white/[0.2] py-8 text-sm text-[#d0cfca]">更多公开文章会在这里陆续出现。</p> : null}</section>
    <section className="mt-14 grid border-y border-white/[0.22] sm:mt-20 sm:grid-cols-3" aria-label="继续探索">{[["归档", "按时间查找", "/archives"], ["标签", "按主题筛选", "/tags"], ["图片集", "查看已公开的图像", "/gallery"]].map(([label, copy, href], index) => <button key={href} onClick={() => navigate(href)} className={`group flex items-center justify-between px-1 py-5 text-left transition-colors hover:bg-white/[0.055] sm:px-6 ${index > 0 ? "border-t border-white/[0.16] sm:border-l sm:border-t-0" : ""}`}><span><span className="block text-sm font-medium text-[#fff8ed]">{label}</span><span className="mt-1 block text-xs text-[#d0cfca]">{copy}</span></span><ArrowRight size={15} className="text-[#d0cfca] transition-transform group-hover:translate-x-1 group-hover:text-[#d0f4ee]" /></button>)}</section>
    <section className="mt-14 grid gap-8 border-l border-[#eab78c] pl-5 sm:mt-20 sm:grid-cols-12 sm:pl-8"><div className="sm:col-span-5"><p className="editorial-kicker">这个站怎么用</p><h2 className="display-title mt-3 text-4xl">从一篇文章，<br />找到一条线索。</h2></div><div className="sm:col-span-6 sm:col-start-7"><p className="copy-lede">文章负责记录过程；标签和归档负责把它们找回来；图片集则留住不适合写进段落里的现场。</p><button onClick={() => navigate("/archives")} className="group mt-7 inline-flex items-center gap-2 border-b border-white/[0.35] pb-1 text-sm text-[#f4ede3] transition-colors hover:border-[#d0f4ee] hover:text-[#d0f4ee]">查看文章归档 <ArrowRight size={15} className="transition-transform group-hover:translate-x-1" /></button></div></section>
  </div>;
}
