/** 地层信号设计基线：文章索引在本地完成筛选和阅读路径，不请求数据库或第三方 API。 */
import { ArrowUpRight, Search, X } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { allTags, staticPosts } from "@/data/site";

export default function StaticPosts() {
  const [query, setQuery] = useState(""); const [activeTag, setActiveTag] = useState<string | null>(null);
  const records = useMemo(() => staticPosts.filter((post) => { const term = query.trim().toLowerCase(); return (!term || [post.title, post.excerpt, post.theme, ...post.tags].join(" ").toLowerCase().includes(term)) && (!activeTag || post.tags.includes(activeTag)); }), [activeTag, query]);
  return <section className="index-page"><div className="index-page__hero"><p className="signal-label">ARCHIVE / ALL PUBLISHED SIGNALS</p><h1 className="display-title">文章索引</h1><p className="lede">这里是已公开技术记录的轻量目录。选择条目后可继续进入原始博客阅读全文。</p></div><div className="index-tools"><label className="search-field"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索标题、主题或标签" /><span>{records.length} RECORDS</span></label><div className="tag-filter" aria-label="按标签筛选"><button onClick={() => setActiveTag(null)} className={!activeTag ? "tag-filter__item tag-filter__item--active" : "tag-filter__item"}>ALL</button>{allTags.map((tag) => <button key={tag} onClick={() => setActiveTag(tag === activeTag ? null : tag)} className={tag === activeTag ? "tag-filter__item tag-filter__item--active" : "tag-filter__item"}>{tag}</button>)}</div></div>{activeTag && <div className="active-filter">正在筛选：#{activeTag}<button onClick={() => setActiveTag(null)} aria-label="清除标签筛选"><X size={14} /></button></div>}<div className="index-list">{records.map((post, index) => <article key={post.slug} className="index-row"><span className="index-row__number">{String(index + 1).padStart(2, "0")}</span><img src={post.cover} alt="" loading="lazy" className="index-row__image" /><div className="index-row__copy"><div className="index-row__meta"><span>{post.theme}</span><time>{post.publishedAt}</time></div><h2>{post.title}</h2><p>{post.excerpt}</p><div className="tag-row">{post.tags.map((tag) => <span key={tag}>#{tag}</span>)}</div></div><Link href={`/notes/${post.slug}`} className="index-row__link" aria-label={`查看 ${post.title} 的索引`}><ArrowUpRight size={19} /></Link></article>)}</div>{records.length === 0 && <div className="empty-state"><p className="signal-label">NO MATCHING SIGNAL</p><p>没有找到匹配的公开记录。换一个关键词或清除筛选后再试。</p></div>}</section>;
}
