import { ArrowDownRight, ArrowUpRight, Github, ListFilter } from "lucide-react";
import { Link } from "wouter";
import { assetUrl, siteLinks, siteThemes, staticPosts } from "@/data/site";

export default function StaticHome() {
  const featured = staticPosts.slice(0, 3);
  return <>
    <section className="hero-section"><div className="hero-section__copy"><p className="signal-label">01 / MORRO — PERSONAL TECHNOLOGY FIELD NOTES</p><h1 className="display-title hero-title">把一次折腾，<br /><span>留成下一次</span>可用的坐标。</h1><p className="lede">MorroBlog 记录自托管、网络、硬件和个人技术实验。它不追赶信息流，只把值得回看的过程放进清晰的档案。</p><div className="hero-actions"><Link href="/posts" className="signal-button">进入技术档案 <ArrowDownRight size={17} /></Link><a href={siteLinks.github} target="_blank" rel="noreferrer" className="text-link"><Github size={16} /> 追踪 GitHub</a></div></div><div className="hero-section__visual"><img src={assetUrl("morro-signal-hero.png")} alt="夜晚工作台上的自托管设备与网络设备" /><div className="hero-section__scrim" /><div className="hero-section__stamp"><span>OBSERVATION</span><strong>2026</strong><span>35.6762°N / 139.6503°E</span></div><div className="contour-lines" aria-hidden="true"><i /><i /><i /><i /></div></div></section>
    <section className="signal-strip" aria-label="技术主题">{siteThemes.map(([number, label, copy]) => <article key={label} className="signal-strip__item"><span className="signal-strip__number">{number}</span><p className="signal-strip__label">{label}</p><p>{copy}</p></article>)}</section>
    <section className="content-section"><div className="section-heading"><div><p className="signal-label">02 / LATEST OBSERVATIONS</p><h2 className="display-title">最新观察，<br />来自已发布的记录。</h2></div><Link href="/posts" className="text-link">完整索引 <ArrowUpRight size={16} /></Link></div><div className="feature-grid">{featured.map((post, index) => <article key={post.slug} className={index === 0 ? "feature-card feature-card--lead" : "feature-card"}><div className="feature-card__image"><img src={post.cover} alt="" loading={index === 0 ? "eager" : "lazy"} /></div><div className="feature-card__body"><div className="feature-card__meta"><span>{String(index + 1).padStart(2, "0")} / {post.theme}</span><time>{post.publishedAt}</time></div><h3>{post.title}</h3><p>{post.excerpt}</p><div className="tag-row">{post.tags.map((tag) => <span key={tag}>#{tag}</span>)}</div><Link href={`/notes/${post.slug}`} className="card-link">阅读索引 <ArrowUpRight size={15} /></Link></div></article>)}</div></section>
    <section className="station-section"><div className="station-section__rule" aria-hidden="true" /><div className="station-section__copy"><p className="signal-label">03 / THE STATION</p><h2 className="display-title">不只是博客。<br />也是 Morro 的<br /><span>技术入口。</span></h2></div><div className="station-section__actions"><p>个人主页保留日常入口；这里把可复用的技术记录重新排序。两处站点共用同一个目标：让下一次打开时，仍能快速找到上一次的判断。</p><div className="station-section__links"><a href={siteLinks.home} target="_blank" rel="noreferrer">访问个人主页 <ArrowUpRight size={16} /></a><a href={siteLinks.blog} target="_blank" rel="noreferrer">查看原始博客 <ArrowUpRight size={16} /></a><Link href="/tags"><ListFilter size={16} /> 按主题浏览</Link></div></div></section>
  </>;
}
