import { useState } from "react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeHighlight from "rehype-highlight";
import "highlight.js/styles/atom-one-dark.css";
import ImageUpload from "./ImageUpload";

interface MarkdownEditorProps { value: string; onChange: (value: string) => void; placeholder?: string; allowImageUpload?: boolean; }

export default function MarkdownEditor({ value, onChange, placeholder = "从这里开始。", allowImageUpload = true }: MarkdownEditorProps) {
  const [activeTab, setActiveTab] = useState("edit");
  const characterCount = value.replace(/\s/g, "").length;
  const insertImage = (url: string) => { if (!url) return; const imageMarkdown = `![image](${url})`; onChange(value.trimEnd() ? `${value.trimEnd()}\n\n${imageMarkdown}\n` : `${imageMarkdown}\n`); };

  return <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
    <div className="flex flex-wrap items-center justify-between gap-3 border-y border-white/[0.22] px-1 py-2.5 sm:px-2"><div className="flex items-center gap-4"><TabsList className="h-auto rounded-none bg-transparent p-0" aria-label="编辑器视图"><TabsTrigger value="edit" className="rounded-none border-b-2 border-transparent px-3 py-1.5 text-xs text-[#d0cfca] data-[state=active]:border-[#d0f4ee] data-[state=active]:bg-transparent data-[state=active]:text-[#d0f4ee]">编辑</TabsTrigger><TabsTrigger value="preview" className="rounded-none border-b-2 border-transparent px-3 py-1.5 text-xs text-[#d0cfca] data-[state=active]:border-[#d0f4ee] data-[state=active]:bg-transparent data-[state=active]:text-[#d0f4ee]">预览</TabsTrigger></TabsList>{allowImageUpload && <ImageUpload onUpload={insertImage} compact />}</div><span className="text-xs text-[#d0cfca]">正文 {characterCount.toLocaleString()} 字</span></div>
    <TabsContent value="edit" className="mt-0"><textarea value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} spellCheck aria-label="文章正文" className="mt-4 min-h-[440px] w-full resize-y border-y border-white/[0.22] bg-[#34454f]/46 px-5 py-6 font-serif text-[17px] leading-9 text-[#fff8ed] placeholder:text-[#c4c6c2] focus:border-[#d0f4ee] focus:outline-none focus:ring-4 focus:ring-[#d0f4ee]/10 sm:min-h-[640px] sm:px-7 sm:py-8" /><p className="mt-3 px-1 text-xs leading-6 text-[#d0cfca]">支持 Markdown。可用 <span className="font-mono text-[#f0ede7]">#</span> 写标题、<span className="font-mono text-[#f0ede7]">```</span> 插入代码块；上传图片后会自动插入到文末。</p></TabsContent>
    <TabsContent value="preview" className="mt-0"><div className="prose-cosmic mt-4 min-h-[640px] border-y border-white/[0.22] bg-[#34454f]/30 px-5 py-7 sm:px-7 sm:py-9">{value ? <ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeHighlight]} components={{ h1: ({ node, ...props }) => <h1 className="mb-6 mt-12 text-3xl" {...props} />, h2: ({ node, ...props }) => <h2 className="mb-5 mt-10 text-2xl" {...props} />, h3: ({ node, ...props }) => <h3 className="mb-4 mt-8 text-xl" {...props} />, p: ({ node, ...props }) => <p className="mb-7" {...props} />, code: ({ node, inline, children, ...props }: any) => inline ? <code className="rounded bg-white/[0.1] px-1.5 py-0.5 text-sm" {...props}>{children}</code> : <code {...props}>{children}</code>, pre: ({ node, ...props }) => <pre className="mb-8 overflow-x-auto p-5 text-sm leading-7" {...props} />, blockquote: ({ node, ...props }) => <blockquote className="mb-8 italic" {...props} />, ul: ({ node, ...props }) => <ul className="mb-7 list-disc space-y-2 pl-6" {...props} />, ol: ({ node, ...props }) => <ol className="mb-7 list-decimal space-y-2 pl-6" {...props} />, table: ({ node, ...props }) => <div className="mb-8 overflow-x-auto"><table className="w-full border-collapse text-sm" {...props} /></div>, th: ({ node, ...props }) => <th className="border border-white/20 bg-white/[0.06] p-3 text-left font-sans text-[#d0f4ee]" {...props} />, td: ({ node, ...props }) => <td className="border border-white/15 p-3" {...props} />, a: ({ node, ...props }) => <a target="_blank" rel="noreferrer" {...props} />, img: ({ node, ...props }) => <img className="my-9 w-full border-y border-white/20" loading="lazy" {...props} /> }}>{value}</ReactMarkdown> : <div className="grid min-h-[520px] place-items-center text-center"><div><p className="text-sm font-medium text-[#f0ede7]">预览会显示在这里</p><p className="mt-3 text-sm text-[#d0cfca]">写下第一句后，就可以切换到预览查看排版。</p></div></div>}</div></TabsContent>
  </Tabs>;
}
